// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "path";
import dotenv from "dotenv";
dotenv.config({
  path: path.resolve(__dirname, "./.env"),
  debug: true
});
import { defineConfig } from "prisma/config";

if (!process.env["DATABASE_URL"]) {
  throw new Error("DATABASE_URL is not set");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});